### ISSUE TITLE
[error] File not found: 'validate-json-action/0.1.0/lib/main.js'

### ISSUE THREAD

**Issue by amardeshbd** [OrRosenblatt/validate-json-action#15]
I'm getting following error form the action:

```
[error]File not found: '/home/runner/work/_actions/OrRosenblatt/validate-json-action/0.1.0/lib/main.js'
```

Here is my action job: https://github.com/amardeshbd/vision.hossainkhan.com/pull/66/checks?check_run_id=661135375

And here is my action config:

```
    # Validates the static API JSON file
    - name: Validate External API Json
      uses: OrRosenblatt/validate-json-action@0.1.0
      with:
        # One or more relative file paths under the repository (seperated by comma) of the JSON files to validate with the schema provided.
        json: ./photos.json
        schema: ./photos-schema.json
```

https://github.com/amardeshbd/vision.hossainkhan.com/blob/cf19c01ee10687e81a6bdba8699f29a5072442e2/.github/workflows/json-api-validator.yml

Not exactly sure what is wrong.

**Comment by amardeshbd** [comment]
Worked using example from README:

```
    # Validates the static API JSON file
    - name: Validate External API Json
      uses: docker://orrosenblatt/validate-json-action:latest
      env:
        # One or more relative file paths under the repository (seperated by comma) of the JSON files to validate with the schema provided.
        INPUT_SCHEMA: ./photos.json
        INPUT_JSONS: ./photos-schema.json
```

The CI build passing now - https://github.com/amardeshbd/vision.hossainkhan.com/pull/66

---- 

The previous example was taken from github sidebar. The example should be updated to match the README.
