### ISSUE TITLE
The github action does not validate JSON with schema.

### ISSUE THREAD

**Issue by amardeshbd** [OrRosenblatt/validate-json-action#16]
After fixing #15, I tried to test the validation step. 

Looks like it's not working, here is the PR with test data that was supposed to fail:
* https://github.com/amardeshbd/vision.hossainkhan.com/pull/67

I have validated the same data using https://www.jsonschemavalidator.net/ and it provides error.

Here is the [console log](https://github.com/amardeshbd/vision.hossainkhan.com/pull/67/checks?check_run_id=661451372) for the action:

```
Run docker://orrosenblatt/validate-json-action:latest
  env:
    INPUT_SCHEMA: ./photos.json
    INPUT_JSONS: ./photos-schema.json
/usr/bin/docker run --name orrosenblattvalidatejsonactionlatest_e8e97d --label c27d31 --workdir /github/workspace --rm -e INPUT_SCHEMA -e INPUT_JSONS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/vision.hossainkhan.com/vision.hossainkhan.com":"/github/workspace" orrosenblatt/validate-json-action:latest

✓ /github/workspace/photos.json
✓ /github/workspace/photos-schema.json

✅ All files were validated successfully.
```

---

Snapshot of workflow file:

```
name: JSON API Validate

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: CI VM Initialized
        run: uname -a

      - name: Validate External API Json
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./photos.json
          INPUT_JSONS: ./photos-schema.json
```
